/*
SQLyog Ultimate v10.00 Beta1
MySQL - 5.7.36 : Database - bookshop
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`bookshop` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `bookshop`;

/*Table structure for table `sales` */

DROP TABLE IF EXISTS `sales`;

CREATE TABLE `sales` (
  `sale_id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_name` varchar(255) NOT NULL,
  `customer_mail` varchar(255) NOT NULL,
  `product_id` int(11) NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `product_price` decimal(10,2) NOT NULL,
  `sale_date` datetime NOT NULL,
  PRIMARY KEY (`sale_id`)
) ENGINE=MyISAM AUTO_INCREMENT=101 DEFAULT CHARSET=latin1;

/*Data for the table `sales` */

insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (1,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','65.22','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (2,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','16.29','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (3,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','55.14','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (4,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','32.67','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (5,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','87.22','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (6,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','16.23','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (7,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','41.80','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (8,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','74.19','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (9,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','79.88','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (10,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','87.69','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (11,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','31.55','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (12,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','58.61','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (13,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','17.67','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (14,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','92.95','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (15,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','78.35','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (16,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','10.39','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (17,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','91.35','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (18,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','77.79','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (19,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','98.51','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (20,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','16.68','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (21,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','12.90','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (22,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','16.24','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (23,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','78.08','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (24,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','66.00','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (25,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','12.86','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (26,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','77.76','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (27,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','69.46','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (28,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','45.39','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (29,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','16.12','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (30,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','78.30','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (31,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','94.60','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (32,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','45.78','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (33,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','44.10','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (34,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','20.56','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (35,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','88.66','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (36,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','29.38','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (37,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','79.50','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (38,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','87.05','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (39,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','17.61','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (40,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','38.63','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (41,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','92.82','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (42,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','30.92','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (43,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','94.71','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (44,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','96.91','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (45,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','83.27','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (46,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','47.78','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (47,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','71.18','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (48,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','63.14','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (49,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','61.34','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (50,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','66.71','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (51,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','35.83','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (52,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','37.48','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (53,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','30.80','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (54,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','39.73','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (55,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','17.17','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (56,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','66.53','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (57,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','89.77','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (58,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','36.18','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (59,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','67.60','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (60,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','17.99','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (61,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','59.47','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (62,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','35.15','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (63,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','37.11','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (64,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','37.99','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (65,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','61.20','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (66,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','51.73','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (67,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','79.57','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (68,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','66.55','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (69,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','39.48','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (70,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','39.71','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (71,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','30.69','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (72,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','66.95','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (73,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','14.57','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (74,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','19.74','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (75,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','25.94','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (76,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','79.91','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (77,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','95.59','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (78,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','28.72','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (79,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','17.05','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (80,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','27.72','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (81,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',1,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','68.75','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (82,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','30.35','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (83,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','20.33','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (84,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','51.57','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (85,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','82.40','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (86,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','20.73','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (87,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','20.31','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (88,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','68.59','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (89,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','81.41','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (90,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','22.22','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (91,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','24.59','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (92,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','81.39','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (93,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','64.81','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (94,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','16.23','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (95,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',1,'Refactoring: Improving the Design of Existing Code','22.11','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (96,'Mia Wyss','mia.wyss@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','94.96','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (97,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','75.74','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (98,'Reto Fanzen','reto.fanzen@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','29.82','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (99,'Leandro BuÃŸmann','leandro.bussmann@no-reply.rexx-systems.com',2,'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design','53.09','2023-06-28 22:46:31');
insert  into `sales`(`sale_id`,`customer_name`,`customer_mail`,`product_id`,`product_name`,`product_price`,`sale_date`) values (100,'Hans SchÃ¤fer','hans.schaefer@no-reply.rexx-systems.com',2,'Refactoring: Improving the Design of Existing Code','45.10','2023-06-28 22:46:31');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
